---
title: "Module 7 Project"
author: "Michael Bevilacqua, Tara Gerjarusak, Baylie Larsen, Benjamin Riccio"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Introduction
In this experiment, the force-length relationship is investigated using muscle force generation in control versus fatigued upper limb muscles. The amount of output force transmitted by input force will be measured for the "arm-level system" at twelve different angles (control/fatigued) to determine how angle, fatigue, and force factor into the output force. Andrew Biewener explains the concept of sonomicrometry, along with the impact of the sarcomere, to expand on the possible impacts of angles and the FL relationship. For example, relating to sarcomeres he writes, "This would imply that fatigued muscles favor force generation at longer lengths, possibly due to stretch of series elastic elements resulting in sarcomeres contracting at a shorter length." (Biewener). The minimal research on this topic, according to Biewener provides a space for more investigation on the factors impacting the FL relationship.

CITE: https://journals.physiology.org/doi/full/10.1152/japplphysiol.00109.2006
 
## Methods
The goals of this experiment were to:
1. Produce isometric force-angle curves for the human forearm flexors undertaking maximum voluntary contractions (MVCs).
2. Compare the angle at which maximum isometric force (Fmax) occurs (θmax) between non-fatigued (i.e., control) and eccentrically fatigued forearm flexors.
3. Discuss the underlying mechanisms resulting in a shift of θmax after eccentric fatigue

To do this, measures of force were taken on each group members elbow flexors, at 12 different angles for a non-fatigued and eccentrically fatigued arm, giving a total of 24 sets of data per group member. The measures of force are the "MVCs", which were collected using Arduino.Then, to analyze the data, maximum force is found for each recording and each angle/individual, then divided by max force to normalize the data. This is then used to compare maximum values across the data, and predict values for each angle, to create a proper hypothesis for the reasoning behind the force-length relation.Data is then graphed to compare data visually and compare control vs fatigue flexors. AIC scores are also used to fit polynomial data throughout the data analysis. 

## Results

## Discussion

## Author Contributions

## References

